import "./globals.css";
import { Nunito } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";

import Navbar from "./components/Navbar/Navbar";
import Toast from "./components/Toast";
import Head from "next/head";
import ClientOnly from "./components/ClientOnly";

import IndividualModal from "./components/IndividualModal";
import CategoryModal from "./components/CategoryModal";

import ReduxProvider from "./components/Providers";
import { store } from "./redux/store";
import UserMenu from "./components/UserMenu";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Procore",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en" data-theme="light">
      <Head>
        <link rel="shortcut icon" href="" />
      </Head>
      <body className={font.className}>
        <ReduxProvider>
          <ClientOnly>
            <Navbar currentUser={currentUser} />
            <Toast />
            <IndividualModal />
            <CategoryModal />
          </ClientOnly>
          <div className="flex flex-row items-center justify-center h-full w-full  ">
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
