import "./globals.css";
import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";

import Navbar from "./components/Navbar/Navbar";
import Socials from "./components/Socials";
import Toast from "./components/Toast";
import Register from "./components/Register";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const font = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Procore",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="" />
      </Head>
      <body className={font.className}>
        <Navbar currentUser={currentUser} />
        <Socials />
        <Toast />
        {children}
      </body>
    </html>
  );
}
